server:
  port: 8002
spring:
  application:
    name: myuserconsumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: myuserconsumer8002
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
myorderprovider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
