spring:
  application:
    name: houseprovider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house
    username: root
    password: ok
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: houseprovider8001
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
